Nelarius/imnodes

imnodes.cpp
Just noticed this small bug when getting a hovered node with IsNodeHovered function :P 
Thank you so much for creating this extension btw!
=> Getting a proper node id with IsNodeHovered function

imnodes.cpp
Right now nodes and links get selected only at the mouse release, I think it's better to process the selection while dragging the select box.
=> Immediately select nodes/links

imnodes.cpp
The selected nodes and links are cleared no matter what window you click in.
This was a problem for me because i had a property window for selected nodes, and whenever i would click in that window to edit a property, it would unselect the node (and links).
This makes it so the click has to happen in the node editor window to cause unselection.
Fixes this issue: https://github.com/Nelarius/imnodes/issues/22
=> Fixes a problem with selections

imnodes.cpp
IsPinHovered did not work correctly if it did not have value, the assert when calling .value() would fail. I changed it so it behaves the same way as IsLinkHovered.
=> Fix IsPinHovered

imnodes.cpp, imnodes.h
I don't think linking pins of the same type is ever a desired behaviour?
=> Don't snap links between pins of the same type & Add more info to IsLinkDropped()

imnodes.cpp, imnodes.h
Followup to https://github.com/Nelarius/imnodes/issues/41
This is a non-breaking change to the imnodes interface. The only changes to the interface are the addition of the AttributeFlag and and optional argument added to `IsLinkCreated()` 
The method I used for getting the link created by the snap in `Link()` feels a bit janky, but it functions as expected and I don't see any other way of getting that info.
I have added light documentation with my changes let me know if you want it explaining further. I've done a reasonable amount of testing and it seems to function fine with all the imnodes features, this is just with my implementation though.
=> Added new AttributeFlag EnableLinkCreationOnSnap

imnodes.cpp
This prevents the creation of links between pins that belong to the same node.
Like below.
=> avoid make link if start pin and end pin in same node

imnodes.cpp, imnodes.h
Returns the screenspace rect of a node
useful if you want to do translate nodes using code (and prevent them from intersecting)
=> added GetNodeDimensions

imnodes.cpp
Fixes IsLinkedDropped getting triggered when using EnableLinkCreationOnSnap and creating new links.
=> Fix IsLinkedDropped triggering incorrectly 

imnodes.cpp, imnodes.h
- Add a float in `Style` for node border thickness
- Add a float in `node.layout_style` for border thickness
- Add remaining values in the `StyleVar` enum for pushing and popping
=> Add node border thickness and add remaining StyleVars

imnodes.cpp
The following are possible actions (bugs) that exist in the current codebase:
- You can hover over nodes, links, and pins while mouse is outside of canvas
- You can select nodes and links while mouse is outside of canvas
- You can begin dragging nodes while mouse is outside of canvas
- You can interact with pins (creating a link) while mouse is outside of canvas
- You can hover over nodes, links, pins while performing a box select
- You can hover over pin and node at the same time
- You can hover over pin and link at the same time
- When simulated middle-click is enabled, you can begin a box selection with middle-click that does not finish when middle mouse button is released
This pull request fixes all of these issues. Please let me know if you would like me to make any changes to the …
=> Fix hovering, selection, dragging, and middle-click box selection bugs

imnodes.cpp
For AttributeFlags_EnableLinkDetachWithDragClick to work the link and pin need to be considered hovered, with the fixes to hovering this was no longer possible.
To fix this I changed the link to also be considered hovered if the pins of the link are hovered. This fixes the issue and improves on the detach behaviour. Previously it was only possible to detach a link from the left side of a pin (where the link was also underneath the mouse), now it is possible to detach by clicking anywhere on the pin.
=> Fix AttributeFlags_EnableLinkDetachWithDragClick not working

.clang-tidy, README.md, example/color_node_editor.cpp, example/hello.cpp, example/main.cpp, example/multi_editor.cpp, example/save_load.cpp, imnodes.cpp, imnodes.h
This codebase grew out of a different project of mine and, unfortunately, I didn't fully transform it to conform to ImGui's style at an early stage -- so to this day, an entirely different coding style is used internally. I figured a full transformation all at once would hurt a little less than frequent incremental changes, so this pr includes some changes to `imnodes.h` as well. As a result, the code should be a bit easier to integrate with C.
So just a heads up @sonoro1234 and @hoffstadt that this change is incoming since this might affect your imnodes integration work 👀
=> Reformat codebase to be more consistent with the style used in ImGui

README.md, imnodes.cpp, imnodes.h, imnodes_internal.h
Adds mini map feature to be used between `BeginNodeEditor` and `EndNodeEditor` with following features:
- provides "low detail" view of nodes/links in the graph as an overlay in the editor canvas
- provides the ability to zoom in and out of this context to view more of the graph than is visible in the normal editor canvas viewport
- scrolling, which scales with zoom (when zoomed out, scrolls the editor context at a faster rate)
- node snapping when clicked: pans clicked node to center of canvas when mini-map node is clicked
- node hovering callback, which can be used to set custom tooltips when hovering the mini map
- separate color variables for the mini map bg/outline and nodes/links
- four positioning options within the editor canvas …
=> Adds node editor MiniMap feature

imnodes.cpp, imnodes.h, imnodes_internal.h
This adds an auto-panning feature, that automatically pans editor view when mouse goes outside the visible editor view bounds while: dragging nodes; making a box selection; or creating links between nodes.
=> Add auto-panning when mouse goes outside the editor while dragging stuff

example/color_node_editor.cpp, imnodes.cpp, imnodes.h, imnodes_internal.h
Change mini-map behavior to work as described in issue #117
Mini-map changes:
* Remove old panning/zooming behavior
* Fit and show full node graph
* Show editor's canvas rect
* On click/drag center editor's canvas to selected location
Color node editor example changes:
* Add menu to change mini-map location
* Add menu to change style
Internal changes:
* Refactor how style variables are backed up to follow ImGui style
NOTE: This is based on top of PR #120, so probably that one should go in first.
=> Change mini-map behavior to work as described in issue #117

imnodes.cpp, imnodes_internal.h
Includes changes from https://github.com/Nelarius/imnodes/pull/124
In v0.4 of ImNodes it is possible to start a link on an pin that already has a link. As part of the input handling changes this is no longer possible, attempting to start a new link simply selects the existing link.
If there is a hovered pin a link should only be considered hovered if that link connects to the hovered pin. This avoids issues where if there is a link behind an unrelated hovered pin it would be considered hovered and cause odd interactions.
=> Fix selection issues with pins overlapping unrelated links. Fix not being able to start new links when there is an existing link on a pin

imnodes.cpp, imnodes.h, imnodes_config.h, imnodes_internal.h
Minimally invasive change to allow pybind11 callback and callback data
Here is what it basically looks like in my project if anyone is curious.  I had to extend py::object to be assignable from NULL and also extend the bool conversion operator to test for Py_None.  I slapped it together over the weekend so I'm sure it can be improved.  The upside is not having to make any modifications to ImNodes source except for adding the conditional typedefs/macros.
CMakeLists.txt:
`target_compile_definitions(${THIS} PRIVATE IMNODES_USER_CONFIG=<imnodes_config.h>)`
imnodes_config.h:
```
#pragma once
#include <pybind11/functional.h>
namespace pybind11 {
inline bool PyWrapper_Check(PyObject *o) { return true; }
class wrapper : public object {
public:
PYBIND11_OBJECT_DEFAULT(wrapper, object, …
```
=> Allow User Defined Callbacks and Custom Header like ImGui #115

CMakeLists.txt, example/multi_editor.cpp, imnodes.cpp, imnodes.h, imnodes_internal.h
Updated version of #72 since I apparently cannot push to that PR anymore. Oh well, I needed the motivation to get this going! :smile: Closes #98.
This PR implements snap-to-grid behavior while dragging nodes. Grid snapping uses a simple nearest-point algorithm that works for negative coordinates. Since the last pull request, I made it fancier, so it now snaps the node you started dragging while you're dragging. It's off by default, and totally configurable based on the grid square width and the style flags.
Primary line drawing is very simple, just colors the origin lines a lighter (or darker) shade. Could likely be extended to draw every `n` lines instead, but that's outside of the scope of this PR. It's off by default but controllable with style flags and colors for those who like the …
=> Add grid snapping, ctrl-select, primary grid coloration

CMakeLists.txt, imnodes.cpp, imnodes_internal.h
- Swap uses of `CMAKE_SOURCE_DIR` for `CMAKE_CURRENT_SOURCE_DIR`
- Detect if running as a sub project
- Add option to build examples, defaults to off if running as a subproject
- Allow custom imgui target name since this can vary because imgui doesn't natively include a CMakeLists.txt
=> Fix CMake config to allow using imnodes as sub project
